{
 "title": "Pi Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ambient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature ?C",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "bme680_metrics{type=\"temperature\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pressure hPa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "bme680_metrics{type=\"pressure\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Humidity %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bme680_metrics{type=\"humidity\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Air quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "IAQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bme680_metrics{type=\"air_quality_score\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "bme680_metrics{type=\"air_quality_score\"}"
    }
   ]
  },
  {
   "title": "IAQ Accuracy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 11 },
   "targets": [
    {
     "expr": "bme680_metrics{type=\"air_quality_score_accuracy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Air quality estimates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CO2 equivalent (estimate)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ppm" }
     ],
     "targets": [
      {
       "expr": "bme680_metrics{type=\"eco2_ppm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Breath VOC equivalent (estimate)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "ppm" }
     ],
     "targets": [
      {
       "expr": "bme680_metrics{type=\"bvoce_ppm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MEM usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "( sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100",
       "legendFormat": "Mem perc."
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  }
 ]
}