global:
  scrape_interval: 1m

  scrape_timeout: 5s

  evaluation_interval: 1m

scrape_configs:
  - job_name: high-freq
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets:
        - "host.docker.internal:9256"

  - job_name: local_apps
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
        - "host.docker.internal:9191"

  - job_name: vio
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets:
        - "host.docker.internal:1337"
