global:
  scrape_interval: 1m

  scrape_timeout: 5s

  evaluation_interval: 1m

scrape_configs:
  - job_name: high-freq
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets:
        - "localhost:9256"
