global:
  scrape_interval: 1m

  scrape_timeout: 5s

  evaluation_interval: 1m

scrape_configs:
  - job_name: low-freq
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets:
        - "localhost:9100"  # node-exporter
        - "192.168.178.20:19090" # esp32 mqtt-to-prom


