global:
  scrape_interval: 1m

  scrape_timeout: 5s

  evaluation_interval: 1m

scrape_configs:
  - job_name: low-freq
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets:
        - "localhost:9100" # node-exporter

  - job_name: high-hf
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
        - "localhost:4242" # balena-sense (bme680)
        - "localhost:8000" # ezo-co2

