global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m

  # How long until a scrape request times out.
  scrape_timeout: 5s

  # How frequently to evaluate rules.
  evaluation_interval: 1m

scrape_configs:
  - job_name: low-freq
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets:
        - "localhost:9100"

  - job_name: high-hf
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
        - "localhost:4242"

