#!/bin/bash
docker stop ezo-co2-exporter
docker rm -f ezo-co2-exporter

docker run \
  --name ezo-co2-exporter \
  --device /dev/ttyS0:/dev/ttyS0:rwm \
  -p 8000:8000 \
  -d \
  --restart always \
  ezo-co2-exporter
