#!/bin/bash

source /home/pi/.env # GRAFANA_ADMIN_PASS defined in env vars

mkdir -p /home/pi/grafana/data

docker stop grafana
docker rm -f grafana

if [ -z "$GRAFANA_ADMIN_PASS" ]; then
  echo "Grafana admin pass not set in env vars, exiting."
  exit 1
fi

docker run -d \
  --net host \
  --name grafana \
  --user 1000:1000 \
  --restart always \
  -v /home/pi/grafana/data:/var/lib/grafana \
  -e "GF_SERVER_ROOT_URL=http://$(hostname)" \
  -e "GF_SECURITY_ADMIN_USER=admin" \
  -e "GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASS" \
  -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
  grafana/grafana
