#!/bin/bash
docker stop prometheus
docker rm -f prometheus
docker run \
    --net host \
    --restart always \
    --name prometheus \
    --user 1000:1000 \
    -d \
    -v /home/pi/prometheus/config:/etc/prometheus \
    -v /home/pi/prometheus/data:/data \
    prom/prometheus \
    --storage.tsdb.path /data \
    --config.file /etc/prometheus/prometheus.yml \
    --storage.tsdb.retention.time 60d

