#!/bin/bash

image=lscr.io/linuxserver/sonarr:arm64v8-latest

docker pull $image
docker stop sonarr
docker rm sonarr

docker run \
    -d \
    -e PUID=0 \
    -e PGID=0 \
    -e UMASK_SET=022 \
    -e TZ=Europe/Amsterdam \
    -p 8989:8989 \
    --restart unless-stopped \
    --name sonarr \
    -v /media/Kingston_2TB/data/sonarr:/config \
    -v /media/Kingston_2TB/series:/tv \
    -v /media/Kingston_2TB/downloads:/data \
    $image


