#!/bin/bash

docker stop jackett
docker rm jackett
docker pull linuxserver/jackett

docker run \
    -d \
    --name jackett \
    -e PUID=0 \
    -e PGID=0 \
    --dns=9.9.9.9 \
    -e TZ=Europe/Amsterdam \
    -v /media/pi/Kingston_2TB/jackett:/config \
    -v /storage/Torrents/blackhole:/downloads \
    -p 9117:9117 \
    --restart unless-stopped \
    linuxserver/jackett

