#!/bin/bash

docker pull linuxserver/radarr
docker stop radarr
docker rm -f radarr

docker run \
    -d \
    -e PUID=0 \
    -e PGID=0 \
    -e UMASK_SET=022 \
    -p 7878:7878 \
    -e TZ=Europe/Amsterdam \
    --restart unless-stopped \
    --name radarr \
    -v /media/Kingston_2TB/data/radarr:/config \
    -v /media/Kingston_2TB/movies:/videos \
    -v /media/Kingston_2TB/downloads:/data \
    linuxserver/radarr:latest

